// Generated by https://quicktype.io

export interface AuthResponse {
    user:  User;
    token: string;
}

export interface User {
    id:        number;
    name:      string;
    email:     string;
    createdAt: Date;
    updatedAt: Date;
}
